### ISSUE TITLE
Migrate atomate/fireworks setup guide to the handbook

### ISSUE THREAD

**Issue by sivonxay** [perssongroup/handbook#14]
This guide:
https://docs.google.com/document/d/1NtJf8ax24-M8INWQZS3Axu9AXxlN07hlD0Gvz2ZEOwk/edit

Perhaps even the rest of the technical documents:
https://sites.google.com/a/lbl.gov/perssongroup/technical-documentation-and-tutorials

**Comment by jdagdelen** [comment]
Let's make sure to create a new page for this and then link to it in the Computing page rather than putting it directly in computing.
