### ISSUE TITLE
Add Savio setup details to computing section

### ISSUE THREAD

**Issue by dwinston** [perssongroup/handbook#7]
Jianli (@jic198), once you figure out how to run your VASP jobs on Savio, can you coordinate with @sivonxay and @jdagdelen to update the guide to ensure new folks know what they need to do in future? Thanks.

**Comment by jic198** [comment]
Sure. No problem :)

**Comment by jdagdelen** [comment]
Is this still needed?

**Comment by jdagdelen** [comment]
I think this has been done.
